### ISSUE TITLE
cm.indexcloud~ dropouts if buffer is being written

### ISSUE THREAD

**Issue by wkc1986** [CircuitMusicLabs/petra#31]
Using the Max Package Manager version, `cm.indexcloud~` plays with a lot of gaps if the `buffer~` is being written into at the same time, as though it can only play one grain at a time, or as though the buffer is mostly empty. Tried with `karma~` and `record~`. It goes back to normal once recording is turned off. I haven't tried the other `buffer~` based objects in the package.

**Comment by CircuitMusicLabs** [comment]
Thanks for your comment! Yes, this is intentional. All three `buffer~` based objects stop generating grains as soon as the `buffer~` is modified. This stopping of the grainstream is absolutely necessary for events such as the `cloudsize` or `grainsize` messages. I'll have a look if this is actually necessary if the `buffer~` was modified. If you're into live granulation in general, it's maybe better if you stick with the `cm.livecloud~` object in the meantime.

**Comment by CircuitMusicLabs** [comment]
It seems it can be done. I just rewrote the buffer-referencing routines and it is now possible to change/replace/overwrite/resize the buffer without interruption of the grain stream. I'm now testing all externals on both platforms and will then push a new beta release.

**Comment by wkc1986** [comment]
Oh wow! Awesome, thanks for looking into it!

**Comment by CircuitMusicLabs** [comment]
I have just released [petra-1.1.5-beta](https://github.com/CircuitMusicLabs/petra/releases/tag/1.1.5-beta), which includes the new buffer-referencing routine. Would you mind checking it out?

**Comment by wkc1986** [comment]
Works beautifully with Max 7 on Mac so far!

**Comment by CircuitMusicLabs** [comment]
Closing issue. Fix is stable.
